name: math802
channels:
  - marufr
  - conda-forge
  - cvxgrp
  - defaults
dependencies:
  - matplotlib=3.0.2
  - python=3.7
  - numpy=1.15.4
  - scipy=1.1.0
  - pylint=2.2.2
  - pytest=4.1.0
  - sympy=1.3
